name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,extra]"
    - name: Task 4.1 - 1D Convolution
      id: task-4-1-1d-convolution
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4.1 - 1D Convolution
        setup-command: ''
        command: python -m pytest -m task4_1 --tb=no -q
        timeout: 15
        max-score: 25
    - name: Task 4.2 - 2D Convolution
      id: task-4-2-2d-convolution
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4.2 - 2D Convolution
        setup-command: ''
        command: python -m pytest -m task4_2 --tb=no -q
        timeout: 15
        max-score: 25
    - name: Task 4.3 - Pooling Operations
      id: task-4-3-pooling-operations
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4.3 - Pooling Operations
        setup-command: ''
        command: python -m pytest -m task4_3 --tb=no -q
        timeout: 15
        max-score: 25
    - name: Task 4.4 - Advanced NN Functions
      id: task-4-4-advanced-nn-functions
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Task 4.4 - Advanced NN Functions
        setup-command: ''
        command: python -m pytest -m task4_4 --tb=no -q
        timeout: 15
        max-score: 15
    - name: Style Check
      id: style-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style Check
        setup-command: ''
        command: python -m ruff check . && python -m pyright
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TASK-4-1-1D-CONVOLUTION_RESULTS: "${{steps.task-4-1-1d-convolution.outputs.result}}"
        TASK-4-2-2D-CONVOLUTION_RESULTS: "${{steps.task-4-2-2d-convolution.outputs.result}}"
        TASK-4-3-POOLING-OPERATIONS_RESULTS: "${{steps.task-4-3-pooling-operations.outputs.result}}"
        TASK-4-4-ADVANCED-NN-FUNCTIONS_RESULTS: "${{steps.task-4-4-advanced-nn-functions.outputs.result}}"
        STYLE-CHECK_RESULTS: "${{steps.style-check.outputs.result}}"
      with:
        runners: task-4-1-1d-convolution,task-4-2-2d-convolution,task-4-3-pooling-operations,task-4-4-advanced-nn-functions,style-check